"""Command-line interface for SHI package."""
import argparse
import sys
from pathlib import Path

try:
    # Try relative imports first (when installed as package)
    from .config import config
    from .processor import SHIProcessor
    from .cleaner import Cleaner
    from .logging import logger
    from .exceptions import SHIError
except ImportError:
    # Fall back to absolute imports (when running as script)
    from src.shi_core.config import config
    from src.shi_core.processor import SHIProcessor
    from src.shi_core.cleaner import Cleaner
    from src.shi_core.logging import logger
    from src.shi_core.exceptions import SHIError

def create_parser() -> argparse.ArgumentParser:
    """Create and configure the argument parser."""
    main_parser = argparse.ArgumentParser(
        prog="SHI",
        description="Automated implementation of Spatial Harmonic Imaging, "
                   "a modality of Multicontrast X-ray Imaging"
    )
    
    subparsers = main_parser.add_subparsers(dest="command", required=True)
    
    # Calculate subcommand
    parser_shi = subparsers.add_parser(
        "calculate",
        help="Execute the SHI method."
    )
    parser_shi.add_argument(
        "-m", "--mask_period",
        required=True,
        type=int,
        help="Number of projected pixels in the mask."
    )
    parser_shi.add_argument(
        "-i", "--images",
        type=str,
        help="Path to sample image(s)"
    )
    parser_shi.add_argument(
        "-f", "--flat",
        type=str,
        help="Path to flat image(s)"
    )
    parser_shi.add_argument(
        "-d", "--dark",
        type=str,
        help="Path to dark image(s)"
    )
    parser_shi.add_argument(
        "-b", "--bright",
        type=str,
        help="Path to bright image(s)"
    )
    parser_shi.add_argument(
        "--all-2d",
        action="store_true",
        help="Execute SHI-2D method in current folder without specifying inputs"
    )
    parser_shi.add_argument(
        "--all-3d",
        action="store_true",
        help="Execute SHI-CT method in current folder without specifying inputs"
    )
    parser_shi.add_argument(
        "--average",
        action="store_true",
        help="Apply averaging"
    )
    parser_shi.add_argument(
        "--export",
        action="store_true",
        help="Export results"
    )
    parser_shi.add_argument(
        "--angle-after",
        action="store_true",
        help="Apply angle correction after measurements"
    )
    parser_shi.add_argument(
        "--unwrap-phase",
        type=str,
        choices=list(config.UNWRAP_METHODS.keys()),
        help="Select phase unwrapping method"
    )
    
    # Clean subcommand
    parser_clean = subparsers.add_parser(
        "clean",
        help="Delete temporary files"
    )
    parser_clean.add_argument(
        "--cache",
        action="store_true",
        help="Clear cache generated by SHI"
    )
    parser_clean.add_argument(
        "--extra",
        action="store_true",
        help="Clear extra files generated after calculate"
    )
    
    return main_parser

def main() -> int:
    """Main entry point for the CLI."""
    parser = create_parser()
    args = parser.parse_args()
    
    try:
        if args.command == "calculate":
            processor = SHIProcessor(
                mask_period=args.mask_period,
                unwrap_method=args.unwrap_phase
            )
            
            if args.all_2d or args.all_3d:
                # Handle automatic mode
                measurement_directory = Path.cwd()
                images_path = measurement_directory / "sample"
                dark_path = measurement_directory / "dark"
                flat_path = measurement_directory / "flat"
                bright_path = measurement_directory / "bright"
                
                mode = "2d" if args.all_2d else "3d"
                
                processor.process_directory(
                    images_path=images_path,
                    dark_path=dark_path if dark_path.exists() else None,
                    flat_path=flat_path if flat_path.exists() else None,
                    bright_path=bright_path if bright_path.exists() else None,
                    mode=mode,
                    angle_after=args.angle_after,
                    average=args.average,
                    export=args.export
                )
            else:
                # Handle manual mode
                processor.process_directory(
                    images_path=args.images,
                    dark_path=args.dark,
                    flat_path=args.flat,
                    bright_path=args.bright,
                    mode="2d",  # default to 2d in manual mode
                    angle_after=args.angle_after,
                    average=args.average,
                    export=args.export
                )
                
        elif args.command == "clean":
            if args.cache:
                Cleaner.clean_cache()
            elif args.extra:
                Cleaner.clean_extra(Path.cwd())
            else:
                raise SHIError("No cleaning option specified. Use --cache or --extra.")
        
        return 0
        
    except Exception as e:
        logger.error(str(e))
        return 1

if __name__ == "__main__":
    sys.exit(main())
