import React, { useState } from 'react';
import { Job } from '../types';
import * as api from '../services/api';
import './CleanForm.css';

interface CleanFormProps {
  onJobCreated: (job: Job) => void;
}

const CleanForm: React.FC<CleanFormProps> = ({ onJobCreated }) => {
  const [formData, setFormData] = useState({
    clear_cache: false,
    clear_extra: false,
  });
  
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string>('');

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: checked,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.clear_cache && !formData.clear_extra) {
      setError('Please select at least one cleanup option');
      return;
    }

    setIsSubmitting(true);
    setError('');

    try {
      const response = await api.runCleanCommand({
        clear_cache: formData.clear_cache,
        clear_extra: formData.clear_extra,
      });

      // Create a job object to add to the list immediately
      const newJob: Job = {
        job_id: response.job_id,
        command: 'clean',
        status: 'pending',
        progress: 0,
        message: 'Cleanup queued',
        created_at: new Date().toISOString(),
        log_messages: [],
      };

      onJobCreated(newJob);

      // Reset form
      setFormData({
        clear_cache: false,
        clear_extra: false,
      });

    } catch (error: any) {
      setError(error.response?.data?.detail || 'Failed to start cleanup');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="clean-form">
      <h3>Clean Command</h3>
      <p className="form-description">
        Deletes temporary files generated by the SHI method. Equivalent to <code>shi clean</code>
      </p>

      <form onSubmit={handleSubmit}>
        {/* Cleanup Options */}
        <div className="form-group">
          <label>Cleanup Operations</label>
          <div className="checkbox-group">
            <label className="checkbox-label">
              <input
                type="checkbox"
                name="clear_cache"
                checked={formData.clear_cache}
                onChange={handleInputChange}
              />
              Clear Cache (--clear-cache)
              <div className="option-help">
                Clear cache files generated by SHI processing. This includes temporary 
                computation results and intermediate processing data.
              </div>
            </label>
            
            <label className="checkbox-label">
              <input
                type="checkbox"
                name="clear_extra"
                checked={formData.clear_extra}
                onChange={handleInputChange}
              />
              Clear Extra Files (--clear-extra)
              <div className="option-help">
                Clear extra files generated by SHI after calculate operations. 
                This helps free up disk space by removing non-essential temporary files.
              </div>
            </label>
          </div>
        </div>

        {error && <div className="error-message">{error}</div>}

        <button
          type="submit"
          disabled={isSubmitting || (!formData.clear_cache && !formData.clear_extra)}
          className="submit-button"
        >
          {isSubmitting ? 'Running Cleanup...' : 'Run Cleanup'}
        </button>
      </form>

      <div className="command-info">
        <h4>About Cleanup Operations</h4>
        <div className="warning-box">
          <h5>⚠️ Warning</h5>
          <p>
            Cleanup operations permanently delete files from your system. 
            Make sure you have saved any important results before running cleanup.
          </p>
        </div>
        
        <div className="info-sections">
          <div className="info-section">
            <h5>Cache Cleanup</h5>
            <p>
              Removes cached computation results and intermediate data stored in the 
              <code>/cache</code> directory. This data is used to speed up repeated 
              calculations but can be safely removed to free disk space.
            </p>
          </div>
          
          <div className="info-section">
            <h5>Extra Files Cleanup</h5>
            <p>
              Removes additional temporary files created during processing operations. 
              These files are not needed after processing is complete and can consume 
              significant disk space for large datasets.
            </p>
          </div>
        </div>

        <div className="disk-space-note">
          <strong>Tip:</strong> Run cleanup regularly after completing analysis 
          to prevent memory shortages and maintain optimal performance.
        </div>
      </div>
    </div>
  );
};

export default CleanForm;